import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal/LegalPageShell";

export const metadata: Metadata = {
  title: "Terms of Service — Verdant",
  description:
    "Read the terms and conditions that govern your use of Verdant's AI mock interview platform.",
};

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" lastUpdated="October 4, 2026">
      <section>
        <h2>1. Agreement to Terms</h2>
        <p className="mt-3">
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of Verdant
          (&quot;Service&quot;), an AI-powered mock interview platform. By creating an account or
          using Verdant, you agree to these Terms and our{" "}
          <a href="/privacy">Privacy Policy</a>.
        </p>
        <p className="mt-3">
          If you do not agree, do not use the Service.
        </p>
      </section>

      <section>
        <h2>2. Eligibility</h2>
        <p className="mt-3">
          You must be at least 13 years old to use Verdant. If you are under 18, you represent
          that you have parental or guardian consent to use the Service. You are responsible for
          maintaining the confidentiality of your account credentials.
        </p>
      </section>

      <section>
        <h2>3. Description of Service</h2>
        <p className="mt-3">
          Verdant provides AI-generated mock interviews, practice sessions, performance feedback,
          and related tools to help you prepare for real interviews. Features may include chat
          interviews today, with voice and video interviews planned for future release.
        </p>
        <p className="mt-3">
          We may modify, suspend, or discontinue any part of the Service at any time, with or
          without notice.
        </p>
      </section>

      <section>
        <h2>4. Accounts</h2>
        <p className="mt-3">You agree to:</p>
        <ul className="mt-3">
          <li>Provide accurate registration information</li>
          <li>Keep your login credentials secure</li>
          <li>Notify us promptly of any unauthorized use of your account</li>
          <li>Accept responsibility for activity that occurs under your account</li>
        </ul>
        <p className="mt-3">
          We reserve the right to suspend or terminate accounts that violate these Terms.
        </p>
      </section>

      <section>
        <h2>5. Acceptable Use</h2>
        <p className="mt-3">You agree not to:</p>
        <ul className="mt-3">
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to reverse engineer, scrape, or abuse our AI systems</li>
          <li>Interfere with or disrupt the Service or its infrastructure</li>
          <li>Share your account or resell access without permission</li>
          <li>Upload malicious code or content that harms others</li>
          <li>Misrepresent Verdant feedback as an official hiring decision</li>
        </ul>
      </section>

      <section>
        <h2>6. AI-Generated Content</h2>
        <p className="mt-3">
          Interview questions, follow-ups, and feedback are generated by AI and may contain
          inaccuracies or incomplete guidance. Verdant is a practice tool — it does not guarantee
          job offers, interview outcomes, or hiring decisions. You are responsible for how you
          use any feedback or suggestions provided.
        </p>
      </section>

      <section>
        <h2>7. Free and Paid Plans</h2>
        <p className="mt-3">
          Verdant may offer a free tier with usage limits and paid plans with additional
          features. Pricing, billing terms, and plan details will be shown at the time of
          purchase. Paid subscriptions renew according to the plan you select unless cancelled
          before the renewal date.
        </p>
      </section>

      <section>
        <h2>8. Intellectual Property</h2>
        <p className="mt-3">
          Verdant and its logos, design, software, and content are owned by us or our licensors
          and are protected by intellectual property laws. You retain ownership of the interview
          answers and content you submit. By using the Service, you grant us a limited license to
          process that content solely to operate and improve the Service.
        </p>
      </section>

      <section>
        <h2>9. Disclaimer of Warranties</h2>
        <p className="mt-3">
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any
          kind, whether express or implied, including merchantability, fitness for a particular
          purpose, and non-infringement. We do not warrant that the Service will be uninterrupted,
          error-free, or that AI feedback will be accurate or complete.
        </p>
      </section>

      <section>
        <h2>10. Limitation of Liability</h2>
        <p className="mt-3">
          To the maximum extent permitted by law, Verdant and its affiliates will not be liable
          for any indirect, incidental, special, consequential, or punitive damages, or any loss
          of profits, data, or opportunities arising from your use of the Service.
        </p>
      </section>

      <section>
        <h2>11. Termination</h2>
        <p className="mt-3">
          You may stop using Verdant and delete your account at any time. We may suspend or
          terminate your access if you violate these Terms or if we discontinue the Service.
          Provisions that by their nature should survive termination will remain in effect.
        </p>
      </section>

      <section>
        <h2>12. Changes to Terms</h2>
        <p className="mt-3">
          We may update these Terms from time to time. When we do, we will update the &quot;Last
          updated&quot; date on this page. Continued use of Verdant after changes means you accept
          the revised Terms.
        </p>
      </section>

      <section>
        <h2>13. Contact</h2>
        <p className="mt-3">
          Questions about these Terms? Contact us at{" "}
          <a href="mailto:legal@verdant.ai">legal@verdant.ai</a>.
        </p>
      </section>
    </LegalPageShell>
  );
}
